name: Update IP Ranges

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
    
jobs:
  update_ip_ranges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update IP ranges
        run: |
          ranges=$(curl -s https://raw.githubusercontent.com/stigvoss/cloud-ip-ranges/main/ranges/azure/public/latest.json)
          dir="Azure"
          
          # Clear the directory
          if [ -d "$dir" ]; then
            rm -r "$dir"
          fi
          # Create the directory if it doesn't exist
          mkdir -p "$dir"
          
          # Parse the JSON and write the IP addresses to files
          echo "$ranges" \
          	| jq -rcM '.values[] | { id: .id, region: .properties.region, addresses: .properties.addressPrefixes }' \
          	| while read -r line
          do
          	# Extract the ID and the IP addresses
            id=$(echo $line | jq -rcM '.id')
            region=$(echo $line | jq -rCM '.region')
            addresses=$(echo $line | jq -rcM '.addresses[]')
            
            # Create a directory for the region if it doesn't exist
            mkdir -p "$dir/$region"
            
            # Prepend with "ipv4, " or "ipv6, " depending on the IP address type
            # Write to a file in the region directory with the ID as the filename
            printf '%b' "$addresses" | sed -r 's/([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/ipv4, \1/g; s/([0-9a-fA-F]*:[0-9a-fA-F:]+)/ipv6, \1/g' >> "$dir/$region/$id.txt"
          done
      - name: Commit service files
        run: |
          git config --global user.name 'Stig Voss'
          git config --global user.email 'stigvoss@users.noreply.github.com'
          git add *
          
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update IP Ranges"
            git push
          fi
